import { inspeccionarDatosNoConfiables } from '../datos-tecnicos/schema.js';
import { jsonCanonico } from '../datos-tecnicos/hash.js';
import type { ResultadoDisenoAsistido, SnapshotDisenoAsistido } from './tipos.js';

const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function informeDisenoJson(snapshot:SnapshotDisenoAsistido,resultado:ResultadoDisenoAsistido):string{return jsonCanonico({formato:'tablerostudio-diseno-asistido',version:1,snapshot:{hash:snapshot.hash,hashBase:snapshot.hashBase,solicitud:snapshot.solicitud,revisiones:snapshot.revisiones.map(r=>({tipo:r.tipo,catalogoId:r.catalogo.id,id:r.id,revision:r.revision,hash:r.hash}))},resultado:{...resultado,resultados:resultado.resultados.map(r=>({...r,analisis:undefined,proyecto:undefined}))}});}
export function leerInformeDisenoJson(texto:string):unknown{if(texto.length>5_000_000)throw new Error('INFORME_DEMASIADO_GRANDE');const x:unknown=JSON.parse(texto);inspeccionarDatosNoConfiables(x);return x;}
export function informeDisenoCsv(resultado:ResultadoDisenoAsistido):string{const q=(x:unknown)=>`"${String(x??'').replaceAll('"','""')}"`;return['orden,id,tipo,estado,pareto,cambios,seccion_total_mm2,in_a,perdida_w,icc_a,limitaciones',...resultado.resultados.map(r=>[r.orden,r.plan.id,r.plan.tipo,r.estado,r.pareto,r.metricas.cambios,r.metricas.seccionTotalMm2,r.metricas.proteccionInA,r.metricas.perdidaW,r.metricas.iccProspectivaA,r.limitaciones.join('; ')].map(q).join(','))].join('\n');}
export function informeDisenoHtml(snapshot:SnapshotDisenoAsistido,resultado:ResultadoDisenoAsistido):string{return`<!doctype html><html lang="es"><meta charset="utf-8"><title>Diseño asistido V9</title><style>body{font:14px system-ui;margin:2rem;color:#17202a}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ccd;padding:.45rem;text-align:left}small{color:#566}</style><h1>Diseño asistido V9</h1><p><b>${esc(snapshot.solicitud.nombre)}</b> · cobertura ${esc(resultado.cobertura)} · ${resultado.evaluados}/${resultado.totalEstimado}</p><p>${esc(resultado.motivoCobertura)}</p><table><thead><tr><th>#</th><th>Plan</th><th>Estado</th><th>Pareto</th><th>Métricas</th><th>Límites</th></tr></thead><tbody>${resultado.resultados.map(r=>`<tr><td>${r.orden}</td><td>${esc(r.plan.tipo)}<br><small>${esc(r.plan.id)}</small></td><td>${esc(r.estado)}</td><td>${r.pareto?'sí':'no'}</td><td>${esc(JSON.stringify(r.metricas))}</td><td>${esc(r.limitaciones.join('; '))}</td></tr>`).join('')}</tbody></table><h2>Trazabilidad</h2><p>BASE ${esc(snapshot.hashBase)}<br>Snapshot ${esc(snapshot.hash)}</p></html>`;}
